apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-myapp
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-myapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
